In [1]:
import sys
from pathlib import Path

import numpy as np
import polars as pl

import matplotlib.pyplot as plt

%load_ext autoreload
%autoreload 2

sys.path.insert(0, "..")
import plasmidtools

Paths

In [2]:
DATA_DIR = Path("../data")
FIG_DIR = DATA_DIR / "figures"
ADDGENE_DIR = DATA_DIR / "addgene"

Pre-processed / pre-calculated data

In [3]:
plasmid_meta = pl.read_csv(ADDGENE_DIR / "mammalian_plasmids.tsv", separator="\t")
plasmid_citations = pl.read_parquet(ADDGENE_DIR / "citations_addgene.parquet")
plasmid_stats = pl.read_parquet(ADDGENE_DIR / "mammalian_plasmids_statistics.parquet")

element_positions = pl.read_parquet(ADDGENE_DIR / "mammalian_plasmids_elements.parquet")
element_citations = pl.read_parquet(ADDGENE_DIR / "citations_addgene_elements.parquet")
primer_positions = pl.read_parquet(ADDGENE_DIR / "mammalian_plasmids_primers.parquet")
primer_citations = pl.read_parquet(ADDGENE_DIR / "citations_addgene_primers.parquet")

cre_annotation = pl.read_parquet(ADDGENE_DIR / "mammalian_plasmids_cre_and_tss.parquet")

element_cre_overlap = (
    pl.read_parquet(ADDGENE_DIR / "mammalian_plasmids_element_cre_overlaps.parquet")
    .join(element_citations[["element_type", "element_name", "n_plasmids", "n_citations"]], left_on=["type", "name"], right_on=["element_type", "element_name"], how="left")
    .with_columns(pl.max_horizontal("tss_fwd_avg_signal", "tss_rev_avg_signal").alias("tss_avg_signal"))
)

primer_cre_overlap = (
    pl.read_parquet(ADDGENE_DIR / "mammalian_plasmids_primers_cre_overlaps.parquet")
    .join(primer_citations[["element_type", "element_name", "n_plasmids", "n_citations"]], left_on=["type", "name"], right_on=["element_type", "element_name"], how="left")
    .with_columns(pl.max_horizontal("tss_fwd_avg_signal", "tss_rev_avg_signal").alias("tss_avg_signal"))
)

Inserts table

In [95]:
plasmid_data = (
    plasmid_meta
    .join(plasmid_citations[["plasmid_id", "n_citations"]], on="plasmid_id", how="left")
    [["plasmid_id", "sequence_id", "plasmid_name", "vector_type", "backbone", "inserts", "n_citations"]]
)

In [96]:
plasmid_data

shape: (80_838, 7)
┌────────────┬─────────────┬──────────────┬──────────────┬─────────────┬─────────────┬─────────────┐
│ plasmid_id ┆ sequence_id ┆ plasmid_name ┆ vector_type  ┆ backbone    ┆ inserts     ┆ n_citations │
│ ---        ┆ ---         ┆ ---          ┆ ---          ┆ ---         ┆ ---         ┆ ---         │
│ i64        ┆ i64         ┆ str          ┆ str          ┆ str         ┆ str         ┆ i64         │
╞════════════╪═════════════╪══════════════╪══════════════╪═════════════╪═════════════╪═════════════╡
│ 100035     ┆ 192913      ┆ pMT3-RhoGC   ┆ Mammalian    ┆ pMT3        ┆ RhoGC D380E ┆ 1           │
│            ┆             ┆ D380E        ┆ Expression   ┆             ┆             ┆             │
│ 100050     ┆ 194451      ┆ pAAV.CaMKIIa ┆ Mammalian    ┆ pAAV        ┆ hChR2(E123T ┆ 2           │
│            ┆             ┆ .ChETA(E123T ┆ Expression   ┆             ┆ /H134R)     ┆             │
│            ┆             ┆ /H134R…      ┆ ||| AAV      ┆             ┆             ┆             │
│ 100034     ┆ 193102      ┆ pMT3-RhoGC   ┆ Mammalian    ┆ pMT3        ┆ RhoGC D380N ┆ 1           │
│            ┆             ┆ D380N        ┆ Expression   ┆             ┆             ┆             │
│ 100027     ┆ 195074      ┆ pcDNA3-Antar ┆ Mammalian    ┆ pcDNA3      ┆ Antares2    ┆ 5           │
│            ┆             ┆ es2 c-myc    ┆ Expression   ┆             ┆             ┆             │
│ 100091     ┆ 197565      ┆ dCas9        ┆ Mammalian    ┆ pcDNA3.3-TO ┆             ┆ 8           │
│            ┆             ┆ plasmid      ┆ Expression   ┆ PO          ┆             ┆             │
│            ┆             ┆              ┆ ||| CRISP…   ┆             ┆             ┆             │
│ 100015     ┆ 192451      ┆ NsvBa        ┆ Mammalian    ┆ pTracer-CMV ┆ NsvBa       ┆ 1           │
│            ┆             ┆              ┆ Expression   ┆ 2, IRES GFP ┆             ┆             │
│ 100049     ┆ 194448      ┆ pAAV.hSynap. ┆ Mammalian    ┆ pAAV        ┆ hChR2(E123T ┆ 2           │
│            ┆             ┆ ChETA(E123T/ ┆ Expression   ┆             ┆ /H134R)     ┆             │
│            ┆             ┆ H134R)…      ┆ ||| AAV      ┆             ┆             ┆             │
│ 100025     ┆ 194289      ┆ pcDNA3.2-DES ┆ Mammalian    ┆ pcDNA3.2/V5 ┆ MatryoshCaM ┆ 1           │
│            ┆             ┆ T-MatryoshCa ┆ Expression   ┆ -DEST       ┆ P6s         ┆             │
│            ┆             ┆ MP6s         ┆              ┆             ┆             ┆             │
│ 100106     ┆ 193262      ┆ pSN21        ┆ Mammalian    ┆ pLM-vexGFP- ┆ vexGFP-P2A- ┆ 1           │
│            ┆             ┆              ┆ Expression   ┆ OCT4        ┆ OCT4 fused  ┆             │
│            ┆             ┆              ┆ ||| Lenti…   ┆             ┆ to a 'we…   ┆             │
│ 100014     ┆ 192450      ┆ NavBp        ┆ Mammalian    ┆ pTracer-CMV ┆ NavBp       ┆ 1           │
│            ┆             ┆              ┆ Expression   ┆ 2, IRES GFP ┆             ┆             │
│ 100033     ┆ null        ┆ pMT3-RhoGC   ┆ Mammalian    ┆ pMT3        ┆ RhoGC E254D ┆ 1           │
│            ┆             ┆ E254D        ┆ Expression   ┆             ┆             ┆             │
│ 100090     ┆ 197562      ┆ DNMT3A-dCas9 ┆ Mammalian    ┆ pcDNA3.3-TO ┆ DNMT3A      ┆ 8           │
│            ┆             ┆              ┆ Expression   ┆ PO          ┆             ┆             │
│            ┆             ┆              ┆ ||| CRISP…   ┆             ┆             ┆             │
│ 100048     ┆ 193827      ┆ pAAV.CAG.LSL ┆ Mammalian    ┆ pAAV-MCS    ┆ tdtomato    ┆ 9           │
│            ┆             ┆ .tdTomato    ┆ Expression   ┆             ┆             ┆             │
│            ┆             ┆              ┆ ||| AAV |…   ┆             ┆             ┆             │
│ …          ┆ …           ┆ …            ┆ …            ┆ …           ┆ …           ┆ …           │
│ 99941      ┆ 197783      ┆ pcDNA3-HA-RE ┆ Mammalian    ┆ pcDNA3.1    ┆ REDD1       ┆ 1           │
│            ┆             ┆ DD1 S103W    ┆ Expression   ┆             ┆             ┆             │
│            ┆             ┆ (#623)       ┆              ┆             ┆             ┆             │
│ 99940      ┆ 198009      ┆ pcDNA3-HA-RE ┆ Mammalian    ┆ pcDNA3.1    ┆ REDD1       ┆ 1           │
│            ┆             ┆ DD1 N187-207 ┆ Expression   ┆             ┆             ┆             │
│            ┆             ┆ (#596…       ┆              ┆             ┆             ┆             │
│ 99942      ┆ 198010      ┆ pcDNA3-HA-RE ┆ Mammalian    ┆ pcDNA3.1    ┆ REDD1       ┆ 1           │
│            ┆             ┆ DD1 S103L    ┆ Expression   ┆             ┆             ┆             │
│            ┆             ┆ (#624)       ┆              ┆             ┆             ┆             │
│ 99943      ┆ 198011      ┆ pcDNA3-HA-RE ┆ Mammalian    ┆ pcDNA3.1    ┆ REDD1       ┆ 1           │
│            ┆             ┆ DD1 S137A    ┆ Expression   ┆             ┆             ┆             │
│            ┆             ┆ (#627)       ┆              ┆             ┆             ┆             │
│ 99945      ┆ 198013      ┆ pcDNA3-HA-RE ┆ Mammalian    ┆ pcDNA3.1    ┆ REDD1       ┆ 1           │
│            ┆             ┆ DD1 P139A    ┆ Expression   ┆             ┆             ┆             │
│            ┆             ┆ (#625)       ┆              ┆             ┆             ┆             │
│ 99939      ┆ 198008      ┆ pcDNA3-HA-RE ┆ Mammalian    ┆ pcDNA3.1    ┆ REDD1       ┆ 1           │
│            ┆             ┆ DD1 N181-211 ┆ Expression   ┆             ┆             ┆             │
│            ┆             ┆ (#595…       ┆              ┆             ┆             ┆             │
│ 99944      ┆ 198012      ┆ pcDNA3-HA-RE ┆ Mammalian    ┆ pcDNA3.1    ┆ REDD1       ┆ 1           │
│            ┆             ┆ DD1 S137D    ┆ Expression   ┆             ┆             ┆             │
│            ┆             ┆ (#628)       ┆              ┆             ┆             ┆             │
│ 99947      ┆ 198015      ┆ pcDNA3-HA-RE ┆ Mammalian    ┆ pcDNA3.1    ┆ REDD1       ┆ 1           │
│            ┆             ┆ DD1 C140S    ┆ Expression   ┆             ┆             ┆             │
│            ┆             ┆ (#622)       ┆              ┆             ┆             ┆             │
│ 99955      ┆ 198128      ┆ pcDNA3.1-TFE ┆ Mammalian    ┆ pcDNA3.1    ┆ TFEB        ┆ 7           │
│            ┆             ┆ B-WT-MYC     ┆ Expression   ┆             ┆             ┆             │
│            ┆             ┆ (#647)       ┆              ┆             ┆             ┆             │
│ 99956      ┆ 198130      ┆ pcDNA3.1-TFE ┆ Mammalian    ┆ pcDNA3.1    ┆ TFEB        ┆ 2           │
│            ┆             ┆ BS122D-MYC   ┆ Expression   ┆             ┆             ┆             │
│            ┆             ┆ (#777)       ┆              ┆             ┆             ┆             │
│ 99946      ┆ 198014      ┆ pcDNA3-HA-RE ┆ Mammalian    ┆ pcDNA3.1    ┆ REDD1       ┆ 1           │
│            ┆             ┆ DD1          ┆ Expression   ┆             ┆             ┆             │
│            ┆             ┆ R133A/P139A  ┆              ┆             ┆             ┆             │
│            ┆             ┆ (#…          ┆              ┆             ┆             ┆             │
│ 99957      ┆ 198131      ┆ pcDNA3.1-TFE ┆ Mammalian    ┆ pcDNA3.1    ┆ TFEB        ┆ 2           │
│            ┆             ┆ BS211A-MYC   ┆ Expression   ┆             ┆             ┆             │
│            ┆             ┆ (#805)       ┆              ┆             ┆             ┆             │
└────────────┴─────────────┴──────────────┴──────────────┴─────────────┴─────────────┴─────────────┘

In [98]:
pl.Config.set_tbl_rows(25)

inserts_auto = (
    element_positions
    .filter(pl.col("element_type") == "CDS")
    .join(plasmid_data, on="sequence_id")

    .sort(["insert_or_backbone", "n_citations"], descending=True)
    .group_by("element_name", maintain_order=True)
    .first()

    [["plasmid_id", "plasmid_name", "vector_type", "backbone", "inserts", "n_citations", "insert_or_backbone", "element_name", "length", "strand", "intervals"]]

    # .filter(pl.col("n_citations") >= 5)

    .with_columns(
        positions=pl.format(
                "[{}]",  # Wrap the final joined string in outer brackets
                pl.col("intervals").list.eval(
                    # Format inner lists: cast to String, join with commas, wrap in brackets
                    pl.format(
                        "[{}]", 
                        pl.element().cast(pl.List(pl.String)).list.join(", ")
                    )
                ).list.join(", ") # Join the formatted inner lists with commas
            )
    )
    .drop("intervals")
)

inserts_auto.write_csv(ADDGENE_DIR / "mammalian_plasmids_inserts_autoannotated.csv")

In [100]:
(
    inserts_auto
    # .filter(pl.col("insert_or_backbone") == "backbone")
    # [["plasmid_name", "backbone", "inserts", "element_name"]]

    # .head(5)
)

shape: (564, 11)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬────────┬────────┬───────────┐
│ plasmid_id ┆ plasmid_na ┆ vector_typ ┆ backbone   ┆ … ┆ element_na ┆ length ┆ strand ┆ positions │
│ ---        ┆ me         ┆ e          ┆ ---        ┆   ┆ me         ┆ ---    ┆ ---    ┆ ---       │
│ i64        ┆ ---        ┆ ---        ┆ str        ┆   ┆ ---        ┆ i64    ┆ i64    ┆ str       │
│            ┆ str        ┆ str        ┆            ┆   ┆ str        ┆        ┆        ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪════════╪════════╪═══════════╡
│ 52961      ┆ lentiCRISP ┆ Mammalian  ┆ Custom     ┆ … ┆ Cas9       ┆ 4104   ┆ 1      ┆ [[4492,   │
│            ┆ R v2       ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 8596]]    │
│            ┆            ┆ ||| Lenti… ┆            ┆   ┆            ┆        ┆        ┆           │
│ 52961      ┆ lentiCRISP ┆ Mammalian  ┆ Custom     ┆ … ┆ PuroR      ┆ 597    ┆ 1      ┆ [[8734,   │
│            ┆ R v2       ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 9331]]    │
│            ┆            ┆ ||| Lenti… ┆            ┆   ┆            ┆        ┆        ┆           │
│ 12253      ┆ pRSV-Rev   ┆ Mammalian  ┆ pRSV-Rev   ┆ … ┆ Rev        ┆ 351    ┆ -1     ┆ [[3233,   │
│            ┆            ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 3584]]    │
│            ┆            ┆ ||| Lenti… ┆            ┆   ┆            ┆        ┆        ┆           │
│ 12251      ┆ pMDLg/pRRE ┆ Mammalian  ┆ pMD        ┆ … ┆ HIV-1 gag  ┆ 1503   ┆ -1     ┆ [[6113,   │
│            ┆            ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 7616]]    │
│            ┆            ┆ ||| Lenti… ┆            ┆   ┆            ┆        ┆        ┆           │
│ 34879      ┆ pCMV(CAT)T ┆ Mammalian  ┆ pCMV       ┆ … ┆ SB100X     ┆ 1023   ┆ 1      ┆ [[856,    │
│            ┆ 7-SB100    ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 1879]]    │
│ 17608      ┆ pRK5-HA-Ub ┆ Mammalian  ┆ pRK5-HA    ┆ … ┆ ubiquitin  ┆ 228    ┆ 1      ┆ [[1018,   │
│            ┆ iquitin-WT ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 1246]]    │
│ 14883      ┆ FUGW       ┆ Mammalian  ┆ HR'CS-G    ┆ … ┆ EGFP       ┆ 717    ┆ 1      ┆ [[3886,   │
│            ┆            ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 3889],    │
│            ┆            ┆ ||| Lenti… ┆            ┆   ┆            ┆        ┆        ┆ [3889,    │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆        ┆ 3892], [… │
│ 61425      ┆ lenti dCAS ┆ Mammalian  ┆ plenti     ┆ … ┆ dCas9      ┆ 4101   ┆ 1      ┆ [[9955,   │
│            ┆ -VP64_Blas ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 9979],    │
│            ┆ t          ┆ ||| Lenti… ┆            ┆   ┆            ┆        ┆        ┆ [9979,    │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆        ┆ 9982], [… │
│ 61425      ┆ lenti dCAS ┆ Mammalian  ┆ plenti     ┆ … ┆ VP64       ┆ 150    ┆ 1      ┆ [[70,     │
│            ┆ -VP64_Blas ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 220]]     │
│            ┆ t          ┆ ||| Lenti… ┆            ┆   ┆            ┆        ┆        ┆           │
│ 27056      ┆ pAAV-Ef1a- ┆ Mammalian  ┆ pAAV       ┆ … ┆ EYFP       ┆ 720    ┆ -1     ┆ [[2282,   │
│            ┆ DIO EYFP   ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 2285],    │
│            ┆            ┆ ||| AAV    ┆            ┆   ┆            ┆        ┆        ┆ [2279,    │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆        ┆ 2282], [… │
│ 11546      ┆ EGFP-LC3   ┆ Mammalian  ┆ pEGFP-C3   ┆ … ┆ LC3B       ┆ 375    ┆ -1     ┆ [[1260,   │
│            ┆            ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 1635]]    │
│ 40753      ┆ pGP-CMV-GC ┆ Mammalian  ┆ pEGFP-N1   ┆ … ┆ GCaMP6s    ┆ 1353   ┆ -1     ┆ [[1861,   │
│            ┆ aMP6s      ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 1870],    │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆        ┆ [1843,    │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆        ┆ 1861], [… │
│ 105553     ┆ pENN.AAV.h ┆ Mammalian  ┆ pAAV       ┆ … ┆ Cre        ┆ 1032   ┆ 1      ┆ [[596,    │
│            ┆ Syn.Cre.WP ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 1628]]    │
│            ┆ RE.hGH     ┆ ||| AAV |… ┆            ┆   ┆            ┆        ┆        ┆           │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …      ┆ …      ┆ …         │
│ 54811      ┆ mEos4a-N1  ┆ Mammalian  ┆ mEos4a-N1  ┆ … ┆ mEos4a     ┆ 684    ┆ 1      ┆ [[702,    │
│            ┆            ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 1386]]    │
│ 60911      ┆ pcDNA4TO-H ┆ Mammalian  ┆ pcDNA4TO   ┆ … ┆ GCN4_v1    ┆ 66     ┆ 1      ┆ [[1234,   │
│            ┆ 2B-SunTag2 ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 1300]]    │
│            ┆ 4x_v1      ┆            ┆            ┆   ┆            ┆        ┆        ┆           │
│ 62177      ┆ pMuLE      ┆ Mammalian  ┆ N/A        ┆ … ┆ IFP1.4     ┆ 987    ┆ 1      ┆ [[4631,   │
│            ┆ Lenti Dest ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 5618]]    │
│            ┆ IFP1.4     ┆ ||| Lenti… ┆            ┆   ┆            ┆        ┆        ┆           │
│ 56639      ┆ ZsYellow1- ┆ Mammalian  ┆ ZsYellow1  ┆ … ┆ ZsYellow1  ┆ 696    ┆ 1      ┆ [[1016,   │
│            ┆ H2B-6      ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 1712]]    │
│ 56578      ┆ mTagYFP-H2 ┆ Mammalian  ┆ mTagYFP    ┆ … ┆ TagYFP     ┆ 720    ┆ 1      ┆ [[992,    │
│            ┆ B-6        ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 1712]]    │
│ 56143      ┆ mNeptune-C ┆ Mammalian  ┆ mNeptune-N ┆ … ┆ mNeptune   ┆ 735    ┆ 1      ┆ [[750,    │
│            ┆ ytERM-N-17 ┆ Expression ┆ 1          ┆   ┆            ┆        ┆        ┆ 1485]]    │
│ 56010      ┆ mPlum-CT6- ┆ Mammalian  ┆ mPlum-C1   ┆ … ┆ mTangerine ┆ 696    ┆ 1      ┆ [[673,    │
│            ┆ C1         ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 1369]]    │
│ 106480     ┆ pSV40-GUS- ┆ Mammalian  ┆ pSV40      ┆ … ┆ GUS        ┆ 1809   ┆ 1      ┆ [[232,    │
│            ┆ P2A-Hygro  ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 2041]]    │
│            ┆            ┆ ||| Plant… ┆            ┆   ┆            ┆        ┆        ┆           │
│ 196953     ┆ h-Menkes   ┆ Mammalian  ┆ Unknown    ┆ … ┆ Rep101     ┆ 951    ┆ 1      ┆ [[12040,  │
│            ┆            ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 12447],   │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆        ┆ [0, 544]] │
│ 182578     ┆ CAG-Mermai ┆ Mammalian  ┆ pUC57      ┆ … ┆ mUkG1      ┆ 678    ┆ 1      ┆ [[1779,   │
│            ┆ d in Tol2  ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 2457]]    │
│            ┆            ┆ ||| Zebra… ┆            ┆   ┆            ┆        ┆        ┆           │
│ 158567     ┆ pB-CAG-PE2 ┆ Mammalian  ┆ pB-CAG     ┆ … ┆ NrsR       ┆ 573    ┆ 1      ┆ [[8725,   │
│            ┆ -NatMX     ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 9298]]    │
│            ┆            ┆ ||| CRISP… ┆            ┆   ┆            ┆        ┆        ┆           │
│ 101132     ┆ pMCP-GPI   ┆ Mammalian  ┆ pMCP       ┆ … ┆ MCP        ┆ 234    ┆ -1     ┆ [[2021,   │
│            ┆ Control    ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 2255]]    │
│            ┆ Plasmid    ┆            ┆            ┆   ┆            ┆        ┆        ┆           │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴────────┴────────┴───────────┘

In [103]:
pl.Config.set_tbl_rows(25)

inserts_auto = (
    element_positions
    .filter(pl.col("element_type") == "CDS")
    .join(plasmid_data, on="sequence_id")

    .sort(["insert_or_backbone", "n_citations"], descending=True)
    # .group_by("element_name", maintain_order=True)
    # .first()

    [["plasmid_id", "plasmid_name", "vector_type", "backbone", "inserts", "n_citations", "insert_or_backbone", "element_name", "length", "strand", "intervals"]]

    # .filter(pl.col("n_citations") >= 5)

    .with_columns(
        positions=pl.format(
                "[{}]",  # Wrap the final joined string in outer brackets
                pl.col("intervals").list.eval(
                    # Format inner lists: cast to String, join with commas, wrap in brackets
                    pl.format(
                        "[{}]", 
                        pl.element().cast(pl.List(pl.String)).list.join(", ")
                    )
                ).list.join(", ") # Join the formatted inner lists with commas
            )
    )
    .drop("intervals")
    .filter(pl.col("insert_or_backbone") == "insert")
)

# inserts_auto["insert_or_backbone"].value_counts()
inserts_auto.write_csv(ADDGENE_DIR / "mammalian_plasmids_inserts_autoannotated.csv")

In [104]:
inserts_auto

shape: (20_272, 11)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬────────┬────────┬───────────┐
│ plasmid_id ┆ plasmid_na ┆ vector_typ ┆ backbone   ┆ … ┆ element_na ┆ length ┆ strand ┆ positions │
│ ---        ┆ me         ┆ e          ┆ ---        ┆   ┆ me         ┆ ---    ┆ ---    ┆ ---       │
│ i64        ┆ ---        ┆ ---        ┆ str        ┆   ┆ ---        ┆ i64    ┆ i64    ┆ str       │
│            ┆ str        ┆ str        ┆            ┆   ┆ str        ┆        ┆        ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪════════╪════════╪═══════════╡
│ 52961      ┆ lentiCRISP ┆ Mammalian  ┆ Custom     ┆ … ┆ Cas9       ┆ 4104   ┆ 1      ┆ [[4492,   │
│            ┆ R v2       ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 8596]]    │
│            ┆            ┆ ||| Lenti… ┆            ┆   ┆            ┆        ┆        ┆           │
│ 52961      ┆ lentiCRISP ┆ Mammalian  ┆ Custom     ┆ … ┆ PuroR      ┆ 597    ┆ 1      ┆ [[8734,   │
│            ┆ R v2       ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 9331]]    │
│            ┆            ┆ ||| Lenti… ┆            ┆   ┆            ┆        ┆        ┆           │
│ 52961      ┆ lentiCRISP ┆ Mammalian  ┆ Custom     ┆ … ┆ Cas9       ┆ 4104   ┆ 1      ┆ [[4492,   │
│            ┆ R v2       ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 8596]]    │
│            ┆            ┆ ||| Lenti… ┆            ┆   ┆            ┆        ┆        ┆           │
│ 48138      ┆ pSpCas9(BB ┆ Mammalian  ┆ PX458      ┆ … ┆ Cas9       ┆ 4101   ┆ 1      ┆ [[6013,   │
│            ┆ )-2A-GFP   ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 9288],    │
│            ┆ (PX458)    ┆ ||| CRISP… ┆            ┆   ┆            ┆        ┆        ┆ [0, 826]] │
│ 48138      ┆ pSpCas9(BB ┆ Mammalian  ┆ PX458      ┆ … ┆ Cas9       ┆ 4101   ┆ 1      ┆ [[6013,   │
│            ┆ )-2A-GFP   ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 9288],    │
│            ┆ (PX458)    ┆ ||| CRISP… ┆            ┆   ┆            ┆        ┆        ┆ [0, 826]] │
│ 42230      ┆ pX330-U6-C ┆ Mammalian  ┆ pUC ori    ┆ … ┆ Cas9       ┆ 4101   ┆ 1      ┆ [[1373,   │
│            ┆ himeric_BB ┆ Expression ┆ vector     ┆   ┆            ┆        ┆        ┆ 5474]]    │
│            ┆ -CBh-hSpCa ┆ ||| CRISP… ┆            ┆   ┆            ┆        ┆        ┆           │
│            ┆ …          ┆            ┆            ┆   ┆            ┆        ┆        ┆           │
│ 42230      ┆ pX330-U6-C ┆ Mammalian  ┆ pUC ori    ┆ … ┆ Cas9       ┆ 4101   ┆ 1      ┆ [[1373,   │
│            ┆ himeric_BB ┆ Expression ┆ vector     ┆   ┆            ┆        ┆        ┆ 5474]]    │
│            ┆ -CBh-hSpCa ┆ ||| CRISP… ┆            ┆   ┆            ┆        ┆        ┆           │
│            ┆ …          ┆            ┆            ┆   ┆            ┆        ┆        ┆           │
│ 62988      ┆ pSpCas9(BB ┆ Mammalian  ┆ PX459      ┆ … ┆ PuroR      ┆ 600    ┆ 1      ┆ [[5145,   │
│            ┆ )-2A-Puro  ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 5745]]    │
│            ┆ (PX459)    ┆ ||| CRISP… ┆            ┆   ┆            ┆        ┆        ┆           │
│            ┆ V2…        ┆            ┆            ┆   ┆            ┆        ┆        ┆           │
│ 62988      ┆ pSpCas9(BB ┆ Mammalian  ┆ PX459      ┆ … ┆ Cas9       ┆ 4101   ┆ 1      ┆ [[927,    │
│            ┆ )-2A-Puro  ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 5028]]    │
│            ┆ (PX459)    ┆ ||| CRISP… ┆            ┆   ┆            ┆        ┆        ┆           │
│            ┆ V2…        ┆            ┆            ┆   ┆            ┆        ┆        ┆           │
│ 62988      ┆ pSpCas9(BB ┆ Mammalian  ┆ PX459      ┆ … ┆ Cas9       ┆ 4101   ┆ 1      ┆ [[927,    │
│            ┆ )-2A-Puro  ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 5028]]    │
│            ┆ (PX459)    ┆ ||| CRISP… ┆            ┆   ┆            ┆        ┆        ┆           │
│            ┆ V2…        ┆            ┆            ┆   ┆            ┆        ┆        ┆           │
│ 12253      ┆ pRSV-Rev   ┆ Mammalian  ┆ pRSV-Rev   ┆ … ┆ Rev        ┆ 351    ┆ -1     ┆ [[3233,   │
│            ┆            ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 3584]]    │
│            ┆            ┆ ||| Lenti… ┆            ┆   ┆            ┆        ┆        ┆           │
│ 12251      ┆ pMDLg/pRRE ┆ Mammalian  ┆ pMD        ┆ … ┆ HIV-1 gag  ┆ 1503   ┆ -1     ┆ [[6113,   │
│            ┆            ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 7616]]    │
│            ┆            ┆ ||| Lenti… ┆            ┆   ┆            ┆        ┆        ┆           │
│ 52962      ┆ lentiCas9- ┆ Mammalian  ┆ pFUGW      ┆ … ┆ Cas9       ┆ 4104   ┆ 1      ┆ [[7199,   │
│            ┆ Blast      ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 11303]]   │
│            ┆            ┆ ||| Lenti… ┆            ┆   ┆            ┆        ┆        ┆           │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …      ┆ …      ┆ …         │
│ 216347     ┆ Peroxisome ┆ Mammalian  ┆ Addgene    ┆ … ┆ iRFP670    ┆ 933    ┆ 1      ┆ [[3886,   │
│            ┆ s-FAST-IRE ┆ Expression ┆ #70113     ┆   ┆            ┆        ┆        ┆ 4819]]    │
│            ┆ S-iRFP670  ┆            ┆            ┆   ┆            ┆        ┆        ┆           │
│ 216349     ┆ pCMV-mCher ┆ Mammalian  ┆ pCMV       ┆ … ┆ mCherry    ┆ 708    ┆ 1      ┆ [[0,      │
│            ┆ ry-RspACFA ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 708]]     │
│            ┆ ST         ┆            ┆            ┆   ┆            ┆        ┆        ┆           │
│ 216420     ┆ pC1-lifeac ┆ Mammalian  ┆ pCDNA3.1   ┆ … ┆ Lifeact    ┆ 51     ┆ 1      ┆ [[1608,   │
│            ┆ t-oROS-HT  ┆ Expression ┆            ┆   ┆            ┆        ┆        ┆ 1659]]    │
│ 237078     ┆ LgBiT-KRAS ┆ Mammalian  ┆ pFN217K    ┆ … ┆ K-Ras      ┆ 567    ┆ -1     ┆ [[300,    │
│            ┆ 4B G12C    ┆ Expression ┆ LgBiT      ┆   ┆            ┆        ┆        ┆ 867]]     │
│            ┆ BiBiT      ┆            ┆ CMV-Hyg    ┆   ┆            ┆        ┆        ┆           │
│            ┆ Ready…     ┆            ┆ Flexi Ve…  ┆   ┆            ┆        ┆        ┆           │
│ 236984     ┆ FKBP-12-Na ┆ Mammalian  ┆ pFC32K     ┆ … ┆ FKBP       ┆ 324    ┆ 1      ┆ [[1064,   │
│            ┆ noLuc      ┆ Expression ┆ Nluc       ┆   ┆            ┆        ┆        ┆ 1067],    │
│            ┆ Vector     ┆            ┆ CMV-neo    ┆   ┆            ┆        ┆        ┆ [1067,    │
│            ┆            ┆            ┆ Flexi(R)   ┆   ┆            ┆        ┆        ┆ 1388]]    │
│            ┆            ┆            ┆ V…         ┆   ┆            ┆        ┆        ┆           │
│ 237076     ┆ LgBiT-KRAS ┆ Mammalian  ┆ pFN217K    ┆ … ┆ K-Ras      ┆ 567    ┆ -1     ┆ [[834,    │
│            ┆ 4B(G12V)   ┆ Expression ┆ LgBiT      ┆   ┆ (G12V)     ┆        ┆        ┆ 867],     │
│            ┆ BiBiT-Read ┆            ┆ CMV-Hyg    ┆   ┆            ┆        ┆        ┆ [831,     │
│            ┆ …          ┆            ┆ Flexi Ve…  ┆   ┆            ┆        ┆        ┆ 834],     │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆        ┆ [300,…    │
│ 237033     ┆ LgBiT-KRAS ┆ Mammalian  ┆ pFN217K    ┆ … ┆ K-Ras      ┆ 567    ┆ -1     ┆ [[834,    │
│            ┆ (G12D)     ┆ Expression ┆ LgBiT      ┆   ┆ (G12V)     ┆        ┆        ┆ 867],     │
│            ┆ Vector     ┆            ┆ CMV-Hyg    ┆   ┆            ┆        ┆        ┆ [831,     │
│            ┆            ┆            ┆ Flexi Ve…  ┆   ┆            ┆        ┆        ┆ 834],     │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆        ┆ [300,…    │
│ 237067     ┆ LgBiT-KRAS ┆ Mammalian  ┆ pFN218K    ┆ … ┆ K-Ras      ┆ 567    ┆ -1     ┆ [[841,    │
│            ┆ (G12V)_SmB ┆ Expression ┆ SmBiT      ┆   ┆ (G12V)     ┆        ┆        ┆ 874],     │
│            ┆ iT-CRAF-RB ┆            ┆ CMV-Blast  ┆   ┆            ┆        ┆        ┆ [838,     │
│            ┆ …          ┆            ┆ Flexi …    ┆   ┆            ┆        ┆        ┆ 841],     │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆        ┆ [307,…    │
│ 237033     ┆ LgBiT-KRAS ┆ Mammalian  ┆ pFN217K    ┆ … ┆ K-Ras      ┆ 567    ┆ -1     ┆ [[300,    │
│            ┆ (G12D)     ┆ Expression ┆ LgBiT      ┆   ┆            ┆        ┆        ┆ 867]]     │
│            ┆ Vector     ┆            ┆ CMV-Hyg    ┆   ┆            ┆        ┆        ┆           │
│            ┆            ┆            ┆ Flexi Ve…  ┆   ┆            ┆        ┆        ┆           │
│ 237036     ┆ LgBiT-p53  ┆ Mammalian  ┆ pFN213K    ┆ … ┆ p53        ┆ 1185   ┆ -1     ┆ [[799,    │
│            ┆ Control    ┆ Expression ┆ LgBiT      ┆   ┆            ┆        ┆        ┆ 1984]]    │
│            ┆ Vector     ┆            ┆ CMV-neo    ┆   ┆            ┆        ┆        ┆           │
│            ┆            ┆            ┆ Flexi Ve…  ┆   ┆            ┆        ┆        ┆           │
│ 237035     ┆ NanoBiT    ┆ Mammalian  ┆ pFC215K    ┆ … ┆ c-Myc      ┆ 1317   ┆ -1     ┆ [[3224,   │
│            ┆ Assay      ┆ Expression ┆ LgBiT      ┆   ┆            ┆        ┆        ┆ 4541]]    │
│            ┆ Vector,    ┆            ┆ CMV-neo    ┆   ┆            ┆        ┆        ┆           │
│            ┆ cMyc       ┆            ┆ Flexi Ve…  ┆   ┆            ┆        ┆        ┆           │
│ 237066     ┆ LgBiT-KRAS ┆ Mammalian  ┆ pFN218K    ┆ … ┆ K-Ras      ┆ 567    ┆ 1      ┆ [[3944,   │
│            ┆ (WT)_SmBiT ┆ Expression ┆ SmBiT      ┆   ┆            ┆        ┆        ┆ 4511]]    │
│            ┆ -CRAF-RBD… ┆            ┆ CMV-Blast  ┆   ┆            ┆        ┆        ┆           │
│            ┆            ┆            ┆ Flexi …    ┆   ┆            ┆        ┆        ┆           │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴────────┴────────┴───────────┘